#!/usr/bin/env bash
#
# Git pre-commit hook
#

if ! make build; then
    echo ''
    echo '❌  [FAIL] Build has failed'
    echo ''
    exit 1
fi

if ! make test; then
    echo ''
    echo '❌  [FAIL] Tests have failed'
    echo ''
    exit 1
fi
