name: Build

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOPATH: /home/runner/go

    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        id: node

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "^1.16.4"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install
        run: make install

      - name: Vet
        run: make vet

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
