name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      GOPATH: /home/runner/go

    steps:
      - name: Set up Node
        uses: actions/setup-node@v2
        id: node

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Install
        run: make install

      - name: Test
        run: make test

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to AWS
        run: |
          make deploy \
            USERNAME=${{ secrets.TRAVELINE_API_USERNAME }} \
            PASSWORD=${{ secrets.TRAVELINE_API_PASSWORD }} \
            AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} \
            AWS_REGION=${{ secrets.AWS_REGION }} \
            NAPTAN_CODE=${{ secrets.NAPTAN_CODE }}

      - name: Update Go report card
        uses: creekorful/goreportcard-action@v1.0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
